name: background_downloader
description: "Extension of Flutter Background Downloader for ease while downloading files"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  device_info_plus: ^10.1.0
  flutter:
    sdk: flutter
  flutter_downloader: ^1.11.7
  path_provider: ^2.1.3
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
